### ISSUE TITLE
Request for v5.1.0 release

### ISSUE THREAD

**Issue by haeber** [upscalesoftware/ext-swoole#2]
Hi, swoole 5.1.0 is out and because there is the following requirement in composer.json it's not possible to use swoole 5.1.0 with this library.
```
    "require": {
        "ext-swoole": "self.version"
    },
```

Would it be possible to create a new version with 5.1.0 or to change this `self.version` constraint, somehow? 

My error:
```
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
  ...
  - upscale/ext-swoole v5.0.3 requires ext-swoole v5.0.3 -> it has the wrong version installed (5.1.0).
  ...
```

Thanks a lot in advance

**Comment by sshymko** [comment]
Done https://github.com/upscalesoftware/ext-swoole/releases/tag/v5.1.0

**Comment by haeber** [comment]
Thanks a lot!
